env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LANG=en_US.UTF-8

matrix:
  include:
  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.0
      - android-25
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    env: CORDOVA_NPM="cordova@6.5.0" SCRIPT_NAME="build-android-v6.sh"

  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.0
      - android-25
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    env: CORDOVA_NPM="cordova@7.1.0" SCRIPT_NAME="build-android-v7.sh"

  - os: osx
    language: objective-c
    osx_image: xcode8.3
    env: CORDOVA_NPM="cordova@6.5.0" SCRIPT_NAME="build-ios-v4.sh"

  - os: osx
    language: objective-c
    osx_image: xcode8.3
    env: CORDOVA_NPM="cordova@7.1.0" SCRIPT_NAME="build-ios-v4.sh"

before_install:
- nvm install 8
- PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH ; export PATH
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yes | sdkmanager "platforms;android-26" ; fi

before_script:
- npm install $CORDOVA_NPM

script:
- sh $SCRIPT_NAME
